//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PEClientContext : DbContext
    {
        public PEClientContext()
            : base("name=PEClientContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tblGrades> tblGrades { get; set; }
        public virtual DbSet<tblLaunchedSurveyQuestions> tblLaunchedSurveyQuestions { get; set; }
        public virtual DbSet<tblLaunchedSurveys> tblLaunchedSurveys { get; set; }
        public virtual DbSet<tblLaunchedTeams> tblLaunchedTeams { get; set; }
        public virtual DbSet<tblLaunchedTeamUsers> tblLaunchedTeamUsers { get; set; }
        public virtual DbSet<tblQuestions> tblQuestions { get; set; }
        public virtual DbSet<tblRoles> tblRoles { get; set; }
        public virtual DbSet<tblSubmissionStatus> tblSubmissionStatus { get; set; }
        public virtual DbSet<tblSurveyCompletes> tblSurveyCompletes { get; set; }
        public virtual DbSet<tblSurveyInstances> tblSurveyInstances { get; set; }
        public virtual DbSet<tblSurveyQuestions> tblSurveyQuestions { get; set; }
        public virtual DbSet<tblSurveyResponses> tblSurveyResponses { get; set; }
        public virtual DbSet<tblSurveys> tblSurveys { get; set; }
        public virtual DbSet<tblTeams> tblTeams { get; set; }
        public virtual DbSet<tblTeamUsers> tblTeamUsers { get; set; }
        public virtual DbSet<tblUserRoles> tblUserRoles { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
    
        public virtual ObjectResult<spAspNetUsers_GetAllStudents_Result> spAspNetUsers_GetAllStudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAspNetUsers_GetAllStudents_Result>("spAspNetUsers_GetAllStudents");
        }
    
        public virtual int spLaunch_Create(string aspNetId, string launchName, Nullable<decimal> surveyId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var launchNameParameter = launchName != null ?
                new ObjectParameter("LaunchName", launchName) :
                new ObjectParameter("LaunchName", typeof(string));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(decimal));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLaunch_Create", aspNetIdParameter, launchNameParameter, surveyIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<spLaunchedSurveys_GetAll_Result> spLaunchedSurveys_GetAll(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLaunchedSurveys_GetAll_Result>("spLaunchedSurveys_GetAll", idParameter);
        }
    
        public virtual ObjectResult<spLaunchedSurveyTeams_GetById_Result> spLaunchedSurveyTeams_GetById(string aspNetId, Nullable<decimal> surveyId)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLaunchedSurveyTeams_GetById_Result>("spLaunchedSurveyTeams_GetById", aspNetIdParameter, surveyIdParameter);
        }
    
        public virtual ObjectResult<spPeerSurveys_GetByAspNetId_Result> spPeerSurveys_GetByAspNetId(string aspNetId)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPeerSurveys_GetByAspNetId_Result>("spPeerSurveys_GetByAspNetId", aspNetIdParameter);
        }
    
        public virtual int spSurvey_Create(string id, string surveyName)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var surveyNameParameter = surveyName != null ?
                new ObjectParameter("SurveyName", surveyName) :
                new ObjectParameter("SurveyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSurvey_Create", idParameter, surveyNameParameter);
        }
    
        public virtual int spSurvey_Delete(string aspNetId, Nullable<decimal> surveyId)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSurvey_Delete", aspNetIdParameter, surveyIdParameter);
        }
    
        public virtual ObjectResult<spSurvey_GetAll_Result> spSurvey_GetAll(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSurvey_GetAll_Result>("spSurvey_GetAll", idParameter);
        }
    
        public virtual ObjectResult<spSurvey_GetById_Result> spSurvey_GetById(string aspNetId, Nullable<decimal> surveyId)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSurvey_GetById_Result>("spSurvey_GetById", aspNetIdParameter, surveyIdParameter);
        }
    
        public virtual int spSurvey_Update(string aspNetId, Nullable<decimal> surveyId, string surveyName)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var surveyIdParameter = surveyId.HasValue ?
                new ObjectParameter("SurveyId", surveyId) :
                new ObjectParameter("SurveyId", typeof(decimal));
    
            var surveyNameParameter = surveyName != null ?
                new ObjectParameter("SurveyName", surveyName) :
                new ObjectParameter("SurveyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSurvey_Update", aspNetIdParameter, surveyIdParameter, surveyNameParameter);
        }
    
        public virtual int spTeam_Create(string aspNetId, string teamName)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var teamNameParameter = teamName != null ?
                new ObjectParameter("TeamName", teamName) :
                new ObjectParameter("TeamName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTeam_Create", aspNetIdParameter, teamNameParameter);
        }
    
        public virtual int spTeam_Delete(string aspNetId, Nullable<decimal> teamId)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("TeamId", teamId) :
                new ObjectParameter("TeamId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTeam_Delete", aspNetIdParameter, teamIdParameter);
        }
    
        public virtual ObjectResult<spTeam_GetAll_Result> spTeam_GetAll(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTeam_GetAll_Result>("spTeam_GetAll", idParameter);
        }
    
        public virtual ObjectResult<spTeam_GetById_Result> spTeam_GetById(string aspNetId, Nullable<decimal> teamId)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("TeamId", teamId) :
                new ObjectParameter("TeamId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTeam_GetById_Result>("spTeam_GetById", aspNetIdParameter, teamIdParameter);
        }
    
        public virtual int spTeam_Update(string aspNetId, Nullable<decimal> teamId, string teamName)
        {
            var aspNetIdParameter = aspNetId != null ?
                new ObjectParameter("AspNetId", aspNetId) :
                new ObjectParameter("AspNetId", typeof(string));
    
            var teamIdParameter = teamId.HasValue ?
                new ObjectParameter("TeamId", teamId) :
                new ObjectParameter("TeamId", typeof(decimal));
    
            var teamNameParameter = teamName != null ?
                new ObjectParameter("TeamName", teamName) :
                new ObjectParameter("TeamName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTeam_Update", aspNetIdParameter, teamIdParameter, teamNameParameter);
        }
    }
}
