//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PEClientContext : DbContext
    {
        public PEClientContext()
            : base("name=PEClientContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGrade> tblGrades { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSubmissionStatu> tblSubmissionStatus { get; set; }
        public virtual DbSet<tblSurveyComplete> tblSurveyCompletes { get; set; }
        public virtual DbSet<tblSurveyInstance> tblSurveyInstances { get; set; }
        public virtual DbSet<tblSurveyQuestion> tblSurveyQuestions { get; set; }
        public virtual DbSet<tblSurveyResponse> tblSurveyResponses1 { get; set; }
        public virtual DbSet<tblSurvey> tblSurveys { get; set; }
        public virtual DbSet<tblTeam> tblTeams { get; set; }
        public virtual DbSet<tblTeamUser> tblTeamUsers { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual int sp_CreateSurvey(string id, string surveyName)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var surveyNameParameter = surveyName != null ?
                new ObjectParameter("SurveyName", surveyName) :
                new ObjectParameter("SurveyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateSurvey", idParameter, surveyNameParameter);
        }
    }
}
