//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaunchedTeams
    {
        public decimal TeamId { get; set; }
        public string Name { get; set; }
        public decimal OwnerId { get; set; }
        public decimal SurveyId { get; set; }
    
        public virtual tblLaunchedSurveys tblLaunchedSurveys { get; set; }
    }
}
