//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaunchedSurveyQuestions
    {
        public decimal SurveyQuestionId { get; set; }
        public decimal SurveyId { get; set; }
        public decimal QuestionId { get; set; }
        public decimal QsIndex { get; set; }
    
        public virtual tblLaunchedQuestions tblLaunchedQuestions { get; set; }
        public virtual tblLaunchedSurveys tblLaunchedSurveys { get; set; }
        public virtual tblLaunchedSurveys tblLaunchedSurveys1 { get; set; }
    }
}
