//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaunchedSurveyQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLaunchedSurveyQuestions()
        {
            this.tblSurveyResponses = new HashSet<tblSurveyResponses>();
        }
    
        public int SurveyQuestionId { get; set; }
        public int SurveyId { get; set; }
        public int QsIndex { get; set; }
        public string Text { get; set; }
    
        public virtual tblLaunchedSurveys tblLaunchedSurveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyResponses> tblSurveyResponses { get; set; }
    }
}
