//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyCompletes
    {
        public int SurveyCompleteId { get; set; }
        public int SurveyId { get; set; }
        public int Reviewee { get; set; }
        public int Reviewer { get; set; }
        public byte SubmissionId { get; set; }
    
        public virtual tblSubmissionStatus tblSubmissionStatus { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual tblUsers tblUsers1 { get; set; }
        public virtual tblSurveys tblSurveys { get; set; }
    }
}
