//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSurvey()
        {
            this.tblSurveyCompletes = new HashSet<tblSurveyComplete>();
            this.tblSurveyQuestions = new HashSet<tblSurveyQuestion>();
            this.tblSurveyQuestions1 = new HashSet<tblSurveyQuestion>();
        }
    
        public decimal SurveyId { get; set; }
        public string Name { get; set; }
        public decimal OwnerId { get; set; }
        public Nullable<decimal> InstanceId { get; set; }
    
        public virtual tblSurveyInstance tblSurveyInstance { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyComplete> tblSurveyCompletes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyQuestion> tblSurveyQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyQuestion> tblSurveyQuestions1 { get; set; }
    }
}
