//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSurveys()
        {
            this.tblSurveyCompletes = new HashSet<tblSurveyCompletes>();
            this.tblSurveyQuestions = new HashSet<tblSurveyQuestions>();
        }
    
        public decimal SurveyId { get; set; }
        public string Name { get; set; }
        public decimal OwnerId { get; set; }
        public Nullable<decimal> InstanceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyCompletes> tblSurveyCompletes { get; set; }
        public virtual tblSurveyInstances tblSurveyInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyQuestions> tblSurveyQuestions { get; set; }
    }
}
