//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyResponses
    {
        public int ResponseId { get; set; }
        public int QuestionId { get; set; }
        public int Reviewee { get; set; }
        public int Reviewer { get; set; }
        public string Text { get; set; }
        public byte GradeId { get; set; }
        public int TeamId { get; set; }
    
        public virtual tblGrades tblGrades { get; set; }
        public virtual tblLaunchedSurveyQuestions tblLaunchedSurveyQuestions { get; set; }
        public virtual tblLaunchedTeams tblLaunchedTeams { get; set; }
    }
}
