//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyResponses
    {
        public decimal ResponseId { get; set; }
        public decimal QuestionId { get; set; }
        public decimal Reviewee { get; set; }
        public decimal Reviewer { get; set; }
        public string Text { get; set; }
        public byte GradeId { get; set; }
    
        public virtual tblGrades tblGrades { get; set; }
        public virtual tblQuestions tblQuestions { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual tblUsers tblUsers1 { get; set; }
    }
}
