//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamUser
    {
        public decimal TeamUserId { get; set; }
        public decimal TeamId { get; set; }
        public decimal UserId { get; set; }
    
        public virtual tblTeam tblTeam { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
