//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRoles
    {
        public int UserRoleId { get; set; }
        public int UserId { get; set; }
        public byte RoleId { get; set; }
    
        public virtual tblRoles tblRoles { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
