//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAspNetUsers_GetStudents
    {
        public string FullName { get; set; }
        public string UserName { get; set; }
        public decimal UserId { get; set; }
    }
}
